"""empty message

Revision ID: 1612b37e40c5
Revises: 9ef45f620ee6
Create Date: 2019-10-28 16:53:03.694147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1612b37e40c5'
down_revision = '9ef45f620ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_email', table_name='data')
    op.create_index(op.f('ix_data_email'), 'data', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_email'), table_name='data')
    op.create_index('ix_data_email', 'data', ['email'], unique=True)
    # ### end Alembic commands ###
