"""empty message

Revision ID: 1618dda15a10
Revises: 1612b37e40c5
Create Date: 2019-10-28 17:32:52.467412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1618dda15a10'
down_revision = '1612b37e40c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'data', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='unique')
    # ### end Alembic commands ###
