"""empty message

Revision ID: 6279201594b8
Revises: 848c8919bef0
Create Date: 2019-10-28 16:50:52.529428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6279201594b8'
down_revision = '848c8919bef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('url1', sa.String(length=120), nullable=True))
    op.drop_column('data', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('url', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('data', 'url1')
    # ### end Alembic commands ###
