"""empty message

Revision ID: 848c8919bef0
Revises: cf05d91908c8
Create Date: 2019-10-21 20:24:28.058019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848c8919bef0'
down_revision = 'cf05d91908c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=12), nullable=True),
    sa.Column('md5_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_email'), 'data', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_email'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
