"""empty message

Revision ID: a55b2286b6bc
Revises: aab9c539ea7a
Create Date: 2019-10-21 18:22:33.943142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55b2286b6bc'
down_revision = 'aab9c539ea7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('stete', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'stete')
    # ### end Alembic commands ###
