"""empty message

Revision ID: cf05d91908c8
Revises: a55b2286b6bc
Create Date: 2019-10-21 18:48:46.787716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf05d91908c8'
down_revision = 'a55b2286b6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('state', sa.String(length=12), nullable=True))
    op.drop_column('data', 'stete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('stete', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.drop_column('data', 'state')
    # ### end Alembic commands ###
